### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by mhsieh**
test

### CODE REVIEW

**Comment by mpkocher** [comment]
The tests can't be found? Perhaps I need to update them? 

https://travis-ci.org/mpkocher/pbcommandR/builds/125157516#L3219

**Comment by mhsieh** [comment]
```
> 
> test_package("pbcommandR")
Error: No tests found for pbcommandR
Execution halted
```

**Comment by mhsieh** [comment]
cc #1

**Comment by mpkocher** [comment]
I did write a few tests. :)

https://github.com/mpkocher/pbcommandR/blob/master/tests/testthat/test.loadToolContract.R

I think within R studio devtools::test() will reinstall the package and run the tests?

**Comment by mpkocher** [comment]
However, there's clearly some issues in the tests and hardcoded paths. I am not familiar enough with core R apis or best practices. 

https://github.com/mpkocher/pbcommandR/blob/master/tests/testthat/test.loadResolvedToolContract.R

**Pull request merged**
